version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - npm install

  build:
    commands:
      - npm run build
      - npx ts-node infra/build/index.ts
artifacts:
  files:
    - "cdk.out/**/*"