version: '2'

services:
  postgres:
    hostname: postgres
    image: postgres:14.6
    ports:
      - '54322:5432'
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: postgres
      PGDATA: /tmp
    volumes:
      - ./containers/postgres/data:/var/lib/postgresql/data