import { CustomerStatusEnum, FacilityStatusEnum } from '../enums';

export const CustomerData = [
  {
    name: 'Michael Johnson',
    country: 'USA',
    streetAddress1: '555 Broad St',
    streetAddress2: 'Apt 301',
    city: 'San Francisco',
    state: 'CA',
    zipCode: '94105',
    phoneNumber: '111-222-3333',
    createdBy: 'Admin',
    status: CustomerStatusEnum.Active,
  },
  {
    name: 'Sophia Martinez',
    country: 'Mexico',
    streetAddress1: '123 Calle Principal',
    streetAddress2: '',
    city: 'Mexico City',
    state: 'DF',
    zipCode: '12345',
    phoneNumber: '555-666-7777',
    createdBy: null,
    status: CustomerStatusEnum.Active,
  },
  {
    name: 'David Lee',
    country: 'Canada',
    streetAddress1: '789 Bay St',
    streetAddress2: '',
    city: 'Vancouver',
    state: 'BC',
    zipCode: 'V6B 1W3',
    phoneNumber: '999-888-7777',
    createdBy: 'Manager',
    status: CustomerStatusEnum.Active,
  },
  {
    name: 'Emily Brown',
    country: 'Australia',
    streetAddress1: '456 King St',
    streetAddress2: 'Suite 100',
    city: 'Sydney',
    state: 'NSW',
    zipCode: '2000',
    phoneNumber: null,
    createdBy: 'Admin',
    status: CustomerStatusEnum.Archived,
  },
  {
    name: 'John Doe',
    country: 'USA',
    streetAddress1: '123 Main St',
    streetAddress2: '',
    city: 'New York',
    state: 'NY',
    zipCode: '10001',
    phoneNumber: '123-456-7890',
    createdBy: 'Admin',
    status: CustomerStatusEnum.Active,
  },
  {
    name: 'Jane Smith',
    country: 'Canada',
    streetAddress1: '456 Maple Ave',
    streetAddress2: '',
    city: 'Toronto',
    state: 'ON',
    zipCode: 'M1X 2X6',
    phoneNumber: null,
    createdBy: 'Manager',
    status: CustomerStatusEnum.Active,
  },
  {
    name: 'Alice Johnson',
    country: 'UK',
    streetAddress1: '789 Oak St',
    streetAddress2: 'Apt 101',
    city: 'London',
    state: 'LDN',
    zipCode: 'SW1A 1AA',
    phoneNumber: '987-654-3210',
    createdBy: 'Admin',
    status: CustomerStatusEnum.Archived,
  },
];

export const FacilityData = [
  {
    name: 'Storage D',
    contactName: null,
    streetAddress1: '321 Oak St',
    streetAddress2: '',
    city: 'Houston',
    state: 'TX',
    country: 'USA',
    zipCode: '77002',
    status: FacilityStatusEnum.Active,
    weight: '2000',
  },
  {
    name: 'Warehouse E',
    contactName: 'James Smith',
    streetAddress1: '987 Maple Ave',
    streetAddress2: '',
    city: 'Toronto',
    state: 'ON',
    country: 'Canada',
    zipCode: 'M5H 2K1',
    status: FacilityStatusEnum.Active,
    weight: '6000',
  },
  {
    name: 'Factory F',
    contactName: 'Emma Wilson',
    streetAddress1: '654 Elm St',
    streetAddress2: '',
    city: 'Melbourne',
    state: 'VIC',
    country: 'Australia',
    zipCode: '3000',
    status: FacilityStatusEnum.Archived,
    weight: '4000',
  },
  {
    name: 'Distribution Center G',
    contactName: 'William Johnson',
    streetAddress1: '741 Pine St',
    streetAddress2: 'Suite 201',
    city: 'Montreal',
    state: 'QC',
    country: 'Canada',
    zipCode: 'H3C 2M9',
    status: FacilityStatusEnum.Active,
    weight: '8000',
  },
  {
    name: 'Warehouse A',
    contactName: 'Bob Johnson',
    streetAddress1: '789 Elm St',
    streetAddress2: '',
    city: 'Los Angeles',
    state: 'CA',
    country: 'USA',
    zipCode: '90001',
    status: FacilityStatusEnum.Active,
    weight: '5000',
  },
  {
    name: 'Storage B',
    contactName: null,
    streetAddress1: '101 Pine St',
    streetAddress2: '',
    city: 'Chicago',
    state: 'IL',
    country: 'USA',
    zipCode: '60601',
    status: FacilityStatusEnum.Active,
    weight: '3000',
  },
  {
    name: 'Factory C',
    contactName: 'Sarah Lee',
    streetAddress1: '246 Oak St',
    streetAddress2: 'Suite 202',
    city: 'London',
    state: 'LDN',
    country: 'UK',
    zipCode: 'SW1A 1AA',
    status: FacilityStatusEnum.Archived,
    weight: '7000',
  },
];
